### ISSUE TITLE
Missing third emoji

### ISSUE THREAD

**Issue by seelder** [SoftwareEngineeringToolDemos/ICSE-2013-V-ISSUE-LIZER#1]
For visual consistency, there should be three emojis.

**Comment by seelder** [comment]
Gargi, is this one OK? When I reverted the other change (per your request) I put it into a state where I could not revert this one.

**Comment by gsrajadh** [comment]
Oh ok. But if there is no original tool how can I have a section which says original tool I got working? Correct me if I am wrong.

**Comment by seelder** [comment]
I asked the professor about these on since I had the same question with one of my own repositories (why include them if there is no code?). I think it is for visual consistency. Someone could go through the repositories quickly and know which ones have VMs and which don't based on whether that third emoji is a checkbox or an "x". Particularly since the first one is a check, I thought we probably want to include the third one so that they know there is no workable vm.

**Comment by gsrajadh** [comment]
Oh ok. Please go through my conversation with the professor over here
https://github.com/SoftwareEngineeringToolDemos/ICSE-2013-V-ISSUE-LIZER/issues/8
I will email you the new repo link. I am really very sorry about the inconvenience .
